language: python

python:
  - "2.7"
  - "3.5"

sudo: false

notifications:
  email: false
 
# Setup dependencies and install package
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n travis-env python=$TRAVIS_PYTHON_VERSION setuptools numpy scipy matplotlib basemap=1.0.7 astropy ephem healpy pandas nose -c conda-forge
  - source activate travis-env
  - python setup.py install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script: 
  - python -c "import skymap; print(skymap.__version__)"
  - echo $DISPLAY
  - nosetests